spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: reservation
    password: reservation
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

outbox:
  poll-fixed-delay-ms: 3000
